### ISSUE TITLE
SAE - Erro ao acessar usar de forma contínua o preview da imagem anexada

### ISSUE THREAD

**Issue by danielpinheiro07** [md-monitoracao-diagnose/Coletor#10]
Após inserir anexos de imagem, observou-se a ocorrência de falhas reincidentes no momento em que foi tentado acesso ao preview da imagem, com aparecimento das seguntesnotificações de erro:
-Access violation at address 008A5863 in module 'ColetaOffline.exe'. Read of address 0000000C.
- Loading bitmap failed.

**Comment by thiagopaiva-md** [comment]
Atividade duplicada.
