### ISSUE TITLE
[CERAN] Link do Executavel e Manual de instalação do APK

### ISSUE THREAD

**Issue by CemachMD** [md-monitoracao-diagnose/Coletor#2]
Foi vendido para CERAN o novo software de Coleta na versão android, por tal é necessário as seguintes informações:

-Link para baixar o APK
-Procedimento para gerar Licença
-Manual de instalação do APK
-Manual de uso do novo coletor

**Comment by CemachMD** [comment]
O cliente está solicitando as informações acima, a solicitação já passou mais de 13 dias.

**Comment by CemachMD** [comment]
Equipamento a se utilizar é o seguinte:
Zenfone 4 MAX da ASUS, com Android 8.0.0

**Comment by thiagopaiva-md** [comment]
João já disponibilizou.
