### ISSUE TITLE
SAE - Ao selecionar ponto indisponível, a linha colapsa e não volta

### ISSUE THREAD

**Issue by felipe-coutto** [md-monitoracao-diagnose/Coletor#6]

**Comment by felipe-coutto** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [[SAE] Limpeza de bugs para apresentação](https://trello.com/c/N5FD8oNU/15-sae-limpeza-de-bugs-para-apresenta%C3%A7%C3%A3o)

**Comment by thiagopaiva-md** [comment]
Resolvido.
